# Generated by Django 2.1 on 2020-02-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='姓名'),
        ),
    ]
