# Generated by Django 2.1 on 2020-02-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='日报ID')),
                ('time', models.DateField()),
                ('plan_of_today', models.TextField()),
                ('working_of_today', models.TextField()),
                ('plan_of_tomorrow', models.TextField()),
                ('output', models.TextField(blank=True, default='')),
                ('unresolved', models.TextField(blank=True, default='')),
                ('time_of_create', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('time_of_update', models.DateTimeField(auto_now_add=True, verbose_name='UpdateTime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
            ],
            options={
                'verbose_name': '日报表',
                'verbose_name_plural': '日报表',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='周报ID')),
                ('time', models.DateField()),
                ('plan_of_this_week', models.TextField()),
                ('working_of_this_week', models.TextField()),
                ('summary_of_this_week', models.TextField(blank=True, default='')),
                ('unresolved', models.TextField()),
                ('self_evaluation', models.TextField()),
                ('improving_methods', models.TextField(blank=True, default='')),
                ('plan_of_next_week', models.TextField()),
                ('remark', models.TextField(blank=True, default='')),
                ('time_of_create', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('time_of_update', models.DateTimeField(auto_now_add=True, verbose_name='UpdateTime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
            ],
            options={
                'verbose_name': '周报表',
                'verbose_name_plural': '周报表',
                'ordering': ['time'],
            },
        ),
    ]
